# Generated by Django 2.0.4 on 2018-04-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstore', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Flower',
        ),
    ]
