# Generated by Django 2.0.4 on 2018-04-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstore', '0005_auto_20180419_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overallCount',
            field=models.IntegerField(default=0),
        ),
    ]
